version: "3.7"

services:
  nginx:
    build: ./docker/nginx/
    container_name: ${NGINX_CONTAINER_NAME}
    ports:
      - 8080:80
    links:
      - app
    volumes:
      - ./:/app

  app:
    build: docker/php-fpm
    container_name: ${APP_CONTAINER_NAME}
    user: 1000:1000
    volumes:
      - ./:/app
    expose:
      - 9000